FROM suborbital/velo:dev as velo
FROM suborbital/sat:dev as sat

FROM node:latest

COPY --from=velo /usr/local/bin/velo /usr/local/bin/velo
COPY --from=sat /usr/local/bin/sat /usr/local/bin/sat

COPY . .

ENTRYPOINT [ "npm", "run", "start" ]