FROM suborbital/velo:vmain as velo
FROM suborbital/sat:vmain as sat

FROM node:latest

COPY --from=velo /usr/local/bin/velo /usr/local/bin/velo
COPY --from=sat /usr/local/bin/sat /usr/local/bin/sat

COPY . .

ENTRYPOINT [ "npm", "run", "start" ]